"""OUTFIT_KEYWORDS and the garment-veto constants derived from it
(verbatim from tag_rules).

The _GARMENT_VETO_* derivations MUST stay in this module, AFTER
OUTFIT_KEYWORDS, so they are computed from the fully-defined table
(pinned by tests/test_tag_rules_pins.py::TestDerivedConstants).
"""

# Outfit tag patterns (checked by substring matching)
OUTFIT_KEYWORDS = [
    "uniform",
    "dress",
    "shirt",
    "blouse",
    "jacket",
    "coat",
    "skirt",
    "pants",
    "shorts",
    "jeans",
    "leggings",
    "bikini",
    "swimsuit",
    "one-piece",
    "lingerie",
    "underwear",
    "bra",
    "panties",
    "thong",
    "stockings",
    "pantyhose",
    "socks",
    "thighhighs",
    "kneehighs",
    "boots",
    "shoes",
    "heels",
    "sandals",
    "sneakers",
    "slippers",
    "hat",
    "cap",
    "beret",
    "crown",
    "tiara",
    "headband",
    "ribbon",
    "bow",
    "hairpin",
    "hair_ornament",
    "glasses",
    "sunglasses",
    "monocle",
    "eyepatch",
    "necklace",
    "choker",
    "collar",
    "tie",
    "necktie",
    "scarf",
    "cape",
    "cloak",
    "apron",
    "gloves",
    "armor",
    "maid",
    "nurse",
    "military",
    "police",
    "school_uniform",
    "serafuku",
    "sailor",
    "blazer",
    "kimono",
    "yukata",
    "chinese_clothes",
    "hanfu",
    "leotard",
    "bodysuit",
    "jumpsuit",
    "overalls",
    "crop_top",
    "tank_top",
    "hoodie",
    "sweater",
    "vest",
    "bare",
    "naked",
    "nude",
    "topless",
    "bottomless",
    "towel",
    "sarong",
    "robe",
    "pajamas",
    "belt",
    "suspenders",
    "garter",
    "wristband",
    "bracelet",
    "earrings",
    "ring",
    "anklet",
    "piercing",
    "mask",
    "bandage",
    "headgear",
    "headpiece",
    "turtleneck",
    "highleg",
    "halterneck",
    "miniskirt",
    "micro_bikini",
    "side-tie",
    "string_bikini",
    "cardigan",
    "backpack",
    "helmet",
    "suit",
    "denim",
    "scrunchie",
    "goggles",
    "brooch",
    "bandaid",
    "armband",
    "veil",
    "formal",
    "casual",
    "revealing_clothes",
    "clothes",
    "eyewear",
    "thighhigh",
    "hakama",
    "buckle",
]

# Garment signals that veto the generic-object background classification in
# categorize_tag (v3.3.4 regression fix): BACKGROUND_DETAIL_TOKENS /
# BACKGROUND_OBJECT_KEYWORDS contain generic nouns (tank, pencil, key, shell,
# winter, ...) that must not steal compound garment tags like tank_top,
# pencil_skirt, key_necklace, or winter_coat. Substring keywords are kept >3
# chars so e.g. "bra" cannot veto "branch"; the short garment words are
# matched as whole tokens instead.
_GARMENT_VETO_KEYWORDS = tuple(k for k in OUTFIT_KEYWORDS if len(k) > 3)
_GARMENT_VETO_TOKENS = {"bra", "hat", "cap", "tie", "bow"}
