import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'

/**
 * Frontend obfuscation engine parity vs the reference site (Audit Target A).
 *
 * The golden vectors were generated by running the SAVED Big Tomato site JS
 * (reference/大番茄图片混淆_files) in node — see
 * backend/tests/test_obfuscation_reference_parity.py for the backend twin and
 * the documented site-side quirks (NaN passwords, legacy astral chars).
 * Here the same vectors drive window.ObfuscateEngine.__internals so the
 * browser engine stays byte-exact with what the real site produces.
 */

const goldenPath = path.resolve(
  __dirname,
  '../../../backend/tests/assets/obfuscation_reference_golden.json',
)
const golden = JSON.parse(fs.readFileSync(goldenPath, 'utf8'))

test.describe('Obfuscation engine — reference-site parity', () => {
  test('pixel scramble and padding are byte-exact with the site output', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('#view-gallery')).toBeVisible()

    const result = await page.evaluate((cases) => {
      const eng = (window as any).ObfuscateEngine.__internals
      const fromB64 = (b64: string) => {
        const raw = atob(b64)
        const out = new Uint8ClampedArray(raw.length)
        for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i)
        return out
      }
      const failures: string[] = []
      for (const c of cases) {
        const original = fromB64(c.original_b64)
        const expected = fromB64(c.encrypted_b64)
        const pass = eng.resolvePassword(c.password, 'big_tomato')

        const scrambled = eng.encryptPixels(original, c.width, c.height, pass)
        const padded = eng.addPadding(scrambled, c.width, c.height, pass.extraWidth, pass.extraHeight)
        if (padded.width !== c.encrypted_width || padded.height !== c.encrypted_height) {
          failures.push(`${c.width}x${c.height} pw='${c.password}': padded dims drifted`)
          continue
        }
        let same = padded.data.length === expected.length
        for (let i = 0; same && i < expected.length; i++) if (padded.data[i] !== expected[i]) same = false
        if (!same) failures.push(`${c.width}x${c.height} pw='${c.password}': encrypt bytes differ`)

        // Decoding the site-encrypted bytes must restore the original.
        const cropped = eng.cropPadding(expected, c.encrypted_width, c.encrypted_height, pass.extraWidth, pass.extraHeight)
        const back = eng.decryptPixels(cropped.data, c.width, c.height, pass)
        let restored = back.length === original.length
        for (let i = 0; restored && i < original.length; i++) if (back[i] !== original[i]) restored = false
        if (!restored) failures.push(`${c.width}x${c.height} pw='${c.password}': cross-decode failed`)
      }
      return failures
    }, golden.pixel_cases)

    expect(result).toEqual([])
  })

  test('text crypto matches the site in both modern and legacy modes', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('#view-gallery')).toBeVisible()

    const result = await page.evaluate((cases) => {
      const eng = (window as any).ObfuscateEngine.__internals
      const failures: string[] = []
      for (const c of cases) {
        if (eng.encryptText(c.value, c.key, false) !== c.modern) failures.push(`modern encrypt key=${c.key}`)
        if (eng.decryptText(c.modern, c.key, false) !== c.value) failures.push(`modern decrypt key=${c.key}`)
        if (eng.encryptText(c.value, c.key, true) !== c.legacy) failures.push(`legacy encrypt key=${c.key}`)
        if (eng.decryptText(c.legacy, c.key, true) !== c.value) failures.push(`legacy decrypt key=${c.key}`)
      }
      return failures
    }, golden.text_cases)

    expect(result).toEqual([])
  })
})
